/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Check if GPU acceleration is available (always false if GPU feature is disabled) */
export declare function isGpuAvailable(): boolean

export declare function runMonteCarlo(scenario: any, options: any): any
